Models/ErrorViewModel.cs
using System;

namespace ECommerceShoppingCart.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerceShoppingCart.Models
{
    public class Item
    {
        public Product Product { get; set; }
        public int Quantity { get; set;}
    }
}

Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerceShoppingCart.Models
{
    public class Product
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set;}
         public string Photo { get; set; }
    }
}

ViewModels/ProductModel.cs
using ECommerceShoppingCart.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerceShoppingCart.ViewModels
{
    public class ProductModel
    {
        public List<Product> _products { get; set; }
        public List<Product> findAll()
        {
            _products = new List<Product>
            {
                new Product()
                {
                    Id = "1",
                    Name = "Flower1",
                    Photo = "thumb1.jpg",
                    Price = 2.80
                },
                new Product()
                {
                    Id = "2",
                    Name = "Flower2",
                    Photo = "thumb2.jpg",
                    Price = 3.80
                },
                new Product()
                {
                    Id = "3",
                    Name = "Flower3",
                    Photo = "thumb3.jpg",
                    Price = 4.80
                }
            };
            return _products;
        }

        public Product find(string id)
        {
            List<Product> products = findAll();
            var prod = products.Where(a => a.Id == id).FirstOrDefault();
            return prod;
        }
    }

    }

Controllers/CartController.cs
using ECommerceShoppingCart.Helpers;
using ECommerceShoppingCart.Models;
using ECommerceShoppingCart.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerceShoppingCart.Controllers
{
    public class CartController : Controller
    {
        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
            return View();
        }

        private int IsExist(string id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
        public IActionResult Buy(string id)
        {
            ProductModel productModel = new ProductModel();
            if (SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart") == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item { Product = productModel.find(id), Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            { 
                List < Item > cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = IsExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Item { Product = productModel.find(id), Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session,"cart",cart);
                }
                return RedirectToAction("Index");
            }
        public IActionResult Remove(string id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = IsExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }
        }
    }

Controllers/CheckoutController.cs
using ECommerceShoppingCart.Helpers;
using ECommerceShoppingCart.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerceShoppingCart.Controllers
{
    public class CheckoutController : Controller
    {
        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
            return View();
        }
    }
}

Controllers/ProductController.cs
using ECommerceShoppingCart.Models;
using ECommerceShoppingCart.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerceShoppingCart.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
                ProductModel productModel = new ProductModel();
                ViewBag.products = productModel.findAll();
                return View();
        }
    }
}

Views/Cart/Index.cshtml
@model IEnumerable<ECommerceShoppingCart.Models.Product>
<h2> Cart Page</h2>

<table class="table table-bordered">

    <tr>
        <th>Option</th>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
        <th>Photo</th>
        <th>Quantity</th>
        <th>Sub Total</th>

    </tr>

    @foreach (var prod in ViewBag.cart)
    {
<tr>
    <td> <a asp-action="Remove" asp-controller="Cart" asp-route-id="@prod.Product.Id">Remove</a></td>
    <td>@prod.Product.Id</td>
    <td>@prod.Product.Name</td>
    <td>@prod.Product.Price</td>
    <td> <img scr="wwwroot/images/@prod.Product.Photo" alt="wwww/images/thumb1.jpg" height="60" width="60" /></td>
    <td>@prod.Quantity</td>
    <td>@(prod.Product.Price*prod.Quantity)</td>

</tr>
    }

   

</table>
<br />
 <a asp-action="index" asp-controller="product">Continue Shopping</a>
 <a asp-action="index" asp-controller="checkout">To Checkout</a>

Views/Checkout/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3> CheckOut Page</h3>

<table>
    <tr>
        <th>
            Total Amount To Pay
        </th>
    </tr>
    <tr>
        <td>
            @ViewBag.total
        </td>
    </tr>
</table>

Views/Product/Index.cshtml
@model IEnumerable<ECommerceShoppingCart.Models.Product>
<h2> My Products </h2>
<table class="table table-bordered">

    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
        <th>Photo</th>
        <th>Buy</th>

    </tr>

    @foreach(var product in ViewBag.products)
            {
<tr>
    <td>@product.Id</td>
    <td>@product.Name</td>
    <td>@product.Price</td>
    <td><img scr="~/images/@product.Photo" height="100" width="100"/></td>
    <td> <a asp-action="Buy" asp-controller="Cart" asp-route-id="@product.Id">Buy</a></td>
</tr>
            }
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerceShoppingCart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">ECommerceShoppingCart</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ECommerceShoppingCart - <a asp-area="" asp-controller="Product" asp-action="Index">Product</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>